---
kind: pipeline
name: rustfmt

steps:
- name: git
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: rustfmt
  image: rust:latest
  commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: test

depends_on:
- rustfmt

steps:
- name: git
  image: docker:git
  commands:
    - git submodule update --recursive --init
- name: test
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: signature
hmac: 96ee373504b5ab43b8317b1adb75412bcc785f4c68c50b82f40fde057fe9237d

...
