---
kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init
- name: test
  image: rust:latest
  commands:
  - export RUST_BACKTRACE=1
  - export GIT_AUTHOR_NAME="drone"
  - export GIT_AUTHOR_EMAIL="drone@exqa.de"
  - cargo build --verbose --all
  - cargo test --verbose --all
- name: generate-coverage
  image: xd009642/tarpaulin:develop-nightly
  commands:
  - export GIT_AUTHOR_NAME="drone"
  - export GIT_AUTHOR_EMAIL="drone@exqa.de"
  - cargo tarpaulin --verbose --out Xml --timeout 300
- name: upload-coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
      files:
      - cobertura.xml
      required: true
- name: bench
  image: rust:latest
  commands:
  - cargo bench
---
kind: signature
hmac: 9dd256bf492a04338c73d3c042607ec66ba1ca0ae353c0bee6f06e6c105cf30d

...
