---
kind: pipeline
name: default

clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init
- name: test
  image: rust:latest
  commands:
  - export RUST_BACKTRACE=1
  - export GIT_AUTHOR_NAME="drone"
  - export GIT_AUTHOR_EMAIL="drone@exqa.de"
  - cargo build --verbose --all
  - cargo test --verbose --all
- name: generate-coverage
  image: xd009642/tarpaulin:develop-nightly
  privileged: true
  commands:
  - export GIT_AUTHOR_NAME="drone"
  - export GIT_AUTHOR_EMAIL="drone@exqa.de"
  - cargo tarpaulin --verbose --out Xml --timeout 300
- name: upload-coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
      files:
      - cobertura.xml
      required: true
- name: package-release
  image: rust:latest
  commands:
  - cargo package
- name: publish-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: target/package/*.crate
    checksum:
    - sha256
    when:
      event:
      - tag
---
kind: signature
hmac: 2e5c720dd6b2a215fa1cd3da686df499e9d43196c807e4c67a170be041e26a6d

...
