---
kind: pipeline
name: rustfmt

steps:
- name: rustfmt
  image: rust:latest
  commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: test

depends_on:
- rustfmt

steps:
- name: test
  image: rust:latest
  pull: always
  environment:
    RUST_BACKTRACE: 1
    GIT_AUTHOR_EMAIL: drone@exqa.de
    GIT_AUTHOR_NAME: drone
  commands:
  - export RUST_BACKTRACE=1
  - export GIT_AUTHOR_NAME="drone"
  - export GIT_AUTHOR_EMAIL="drone@exqa.de"
  - cargo build --verbose --all
  - cargo test --verbose --all

- name: matrix-notification
  image: plugins/matrix
  pull: always
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure
---
kind: pipeline
name: coverage

depends_on:
- rustfmt

steps:
- name: generate-coverage
  image: xd009642/tarpaulin:develop-nightly
  pull: always
  privileged: true
  environment:
    GIT_AUTHOR_EMAIL: drone
    GIT_AUTHOR_NAME: drone@exqa.de
  commands:
  - cargo tarpaulin --verbose --out Xml --timeout 3000

- name: upload-coverage
  image: plugins/codecov
  pull: always
  settings:
    token:
      from_secret: codecov_token
      files:
      - cobertura.xml
      required: true

- name: matrix-notification
  image: plugins/matrix
  settings:
    roomid: qOcHPTCOgAbkObQgRy:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
     - failure
---
kind: signature
hmac: 8e2012cc8e985094f8bbd143142e6463fa79741768106fedabe22af8d0c34784

...
