---
kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init
- name: test
  image: rust:latest
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
- name: generate-coverage
  image: tarpaulin:latest
  commands:
  - cargo tarpaulin --verbose --out Xml --timeout 300
- name: upload-coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
      files:
      - cobertura.xml
      required: true
- name: bench
  image: rust:latest
  commands:
  - cargo bench
---
kind: signature
hmac: 5ee02147d763cce35913ad59ea7862f458d3478312040fca97353c834fd3ed0b

...
