language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

script:
  - cargo clean
  - cargo build
  - cargo test

before_install:
  - mkdir vendor
  - pushd vendor
  - git clone https://github.com/Cogitri/crates_io_api
  - popd

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
  # About exclude-files: vendor doesn't belong to use. types&errors.rs don't
  # contain anything we can test.
  # src/bin/* - https://github.com/xd009642/tarpaulin/issues/176
    env LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH cargo tarpaulin \
      --verbose \
      --out Xml \
      --ciserver travis-ci \
      --timeout 240 \
      --exclude-files vendor/* src/lib/types.rs src/lib/errors.rs src/bin/*

    bash <(curl -s https://codecov.io/bash)
  fi
