language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
cache: cargo

script:
  - cargo clean
  - cargo build
  - cargo test
