[package]
name = "tmplgen"
version = "0.2.1"
authors = ["Rasmus Thomsen <rasmus.thomsen@protonmail.com>"]
description = "Generate Void Linux templates"
homepage = "https://github.com/Cogitri/tmplgen"
repository = "https://github.com/Cogitri/tmplgen"
readme = "README.md"
license = "GPL-3.0-or-later"

[dependencies]
crates_io_api = "^0.3.0"
clap = {version = "^2.32", features = ["yaml"]}
rubygems_api = "^0.1.0"
failure = "^0.1.3"
log = "^0.4.6"
env_logger = "^0.5.13"