[package]
name = "tmplgen"
version = "0.4.1"
authors = ["Rasmus Thomsen <rasmus.thomsen@protonmail.com>"]
description = "Void Linux template generator for language-specific package managers"
homepage = "https://github.com/Cogitri/tmplgen"
repository = "https://github.com/Cogitri/tmplgen"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["binary", "cli", "linux", "void-linux"]
categories = ["command-line-utilities"]

[dependencies]
crates_io_api = { path="vendor/crates_io_api", version="0.3.0" }
clap = {version = "^2.32", features = ["yaml"]}
rubygems_api = "^0.1.0"
failure = "^0.1.3"
log = "^0.4.6"
env_logger = {version= "^0.6.0", features = ["termcolor"]}
metacpan_api = "^0.1.0"

[dev-dependencies]
cargo-husky = {version = "^1.2.0", features = ["precommit-hook", "run-cargo-test"]}

[badges]
travis-ci = { repository = "Cogitri/tmplgen" }
codecov = { repository = "https://codecov.io/gh/Cogitri/tmplgen" }
